// Layouts for any number of items (1 to 75), generated by the rule in app/js/core/sheetlayout.js.
const test = require("node:test");
const assert = require("node:assert/strict");
const { load } = require("./helpers/load");

const c = load();
const run = (code) => c.run(code);
const MAX = run("MAX_ITEMS");
const W = 1000, H = (W * run("LAYOUTS['30'].r")) / run("LAYOUTS['30'].ry"), R = run("LAYOUTS['30'].r") * W;
const lay = (n) => run(`layoutFor(${n})`);

test("the rule reproduces the built-in 30, 50 and 60-item sheets", () => {
  for (const n of [30, 50, 60]) {
    const built = run(`LAYOUTS["${n}"]`), rule = run(`layoutByRule(${n})`);
    assert.equal(rule.items.length, built.items.length);
    let worst = 0;
    built.items.forEach((g, i) => g.forEach((p, j) => { worst = Math.max(worst, Math.abs(p[0] - rule.items[i][j][0]), Math.abs(p[1] - rule.items[i][j][1])); }));
    assert.ok(worst < 0.0015, `${n} items: ${worst} off (a bubble radius is 0.012)`);
  }
});

test("the three built-in sheets are returned exactly as stored", () => {
  for (const n of [30, 50, 60]) assert.equal(run(`layoutFor(${n}) === LAYOUTS["${n}"]`), true);
});

test("shapes: 10 rows per column to 50 items, then 12, then 15", () => {
  const s = (n) => run(`sheetShape(${n})`);
  assert.deepEqual({ ...s(1) }, { rows: 1, cols: 1 });
  assert.deepEqual({ ...s(10) }, { rows: 10, cols: 1 });
  assert.deepEqual({ ...s(20) }, { rows: 10, cols: 2 });
  assert.deepEqual({ ...s(25) }, { rows: 10, cols: 3 });
  assert.deepEqual({ ...s(40) }, { rows: 10, cols: 4 });
  assert.deepEqual({ ...s(45) }, { rows: 10, cols: 5 });
  assert.deepEqual({ ...s(50) }, { rows: 10, cols: 5 });
  assert.deepEqual({ ...s(55) }, { rows: 12, cols: 5 });
  assert.deepEqual({ ...s(60) }, { rows: 12, cols: 5 });
  assert.deepEqual({ ...s(61) }, { rows: 15, cols: 5 });
  assert.deepEqual({ ...s(75) }, { rows: 15, cols: 5 });
});

test("a sheet never needs more than five columns", () => {
  for (let n = 1; n <= MAX; n++) assert.ok(run(`sheetShape(${n}).cols`) <= 5, String(n));
});

test("lengths outside 1 to 75 are refused", () => {
  for (const n of [0, -1, 76, 100, 2.5]) assert.throws(() => run(`layoutByRule(${n})`), /A sheet has 1 to 75 items/, String(n));
  assert.throws(() => run(`layoutByRule("40")`), /A sheet has/);
});

test("every length from 1 to 75: right number of items, four choices each, class number and test set", () => {
  for (let n = 1; n <= MAX; n++) {
    const l = lay(n);
    assert.equal(l.items.length, n, `${n} items`);
    assert.ok(l.items.every((g) => g.length === 4), `${n}: four choices`);
    assert.equal(l.cls.length, 2); assert.equal(l.set.length, 4);
  }
});

test("every length: all bubbles sit inside the frame, clear of the header and the corner squares", () => {
  for (let n = 1; n <= MAX; n++) {
    for (const g of lay(n).items) for (const [x, y] of g) {
      assert.ok(x * W - R > 12 && x * W + R < W - 12, `${n}: x ${x} inside the answer box`);
      assert.ok(y > 0.529 - 1e-9 && y * H + R < H * 0.93, `${n}: y ${y} inside the answer area`);
    }
  }
});

test("every length: no two bubbles overlap, with a visible gap", () => {
  for (let n = 1; n <= MAX; n++) {
    const pts = lay(n).items.flat().map(([x, y]) => [x * W, y * H]);
    let min = Infinity;
    for (let i = 0; i < pts.length; i++) for (let j = i + 1; j < pts.length; j++) min = Math.min(min, Math.hypot(pts[i][0] - pts[j][0], pts[i][1] - pts[j][1]));
    assert.ok(min > 2 * R + 6, `${n} items: closest bubbles are ${min.toFixed(1)} apart, a bubble is ${2 * R} wide`);
  }
});

test("every length: items are numbered down each column, then across", () => {
  for (const n of [12, 25, 40, 55, 70, 75]) {
    const l = lay(n), rows = run(`sheetShape(${n}).rows`);
    l.items.forEach((g, i) => {
      if (i % rows) { assert.ok(g[0][1] > l.items[i - 1][0][1], `${n}: item ${i + 1} is below item ${i}`); assert.ok(Math.abs(g[0][0] - l.items[i - 1][0][0]) < 1e-9, `${n}: same column`); }
      else if (i) assert.ok(g[0][0] > l.items[i - 1][0][0], `${n}: item ${i + 1} starts the next column to the right`);
    });
  }
});

test("columns are centred on the sheet and spaced so that neighbours do not touch", () => {
  for (let n = 1; n <= MAX; n++) {
    const xs = [...new Set(lay(n).items.map((g) => g[0][0].toFixed(5)))].map(Number).sort((a, b) => a - b);
    const mid = (xs[0] + xs[xs.length - 1]) / 2;
    assert.ok(Math.abs(mid - 0.4775) < 0.002, `${n}: centred`); // the stored 30, 50 and 60-item layouts are rounded, so allow 0.2% of the frame
    for (let i = 1; i < xs.length; i++) assert.ok((xs[i] - xs[i - 1]) * W > 3 * 34.8 + 2 * R + 45, `${n}: columns ${i} and ${i + 1} leave room for item numbers`);
  }
});

test("a sheet with more items has bubbles at least as close together vertically, but never overlapping", () => {
  const step = (n) => { const l = lay(n); return (l.items[1][0][1] - l.items[0][0][1]) * H; };
  assert.ok(step(75) < step(60) && step(60) < step(50));
  assert.ok(step(75) > 2 * R + 6, `${step(75).toFixed(1)} units between rows of a 75-item sheet`);
});

test("class number and test set are the same on every sheet", () => {
  const base = JSON.stringify(run("LAYOUTS['30'].cls")) + JSON.stringify(run("LAYOUTS['30'].set"));
  for (const n of [5, 20, 40, 75]) assert.equal(JSON.stringify(lay(n).cls) + JSON.stringify(lay(n).set), base);
});
